### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by chairco** [g0v/vue.vtaiwan.tw#3]
目前 git clone 下來，直接  `npm i` 會有下列錯誤

```
npm ERR! notarget No compatible version found: node-bourbon@^3.10.5
npm ERR! notarget Valid install targets:
npm ERR! notarget 4.2.8, 4.2.7, 4.2.6, 4.2.3, 4.2.2, 4.2.1, 4.2.1-beta1, 1.2.3, 1.2.2, 1.2.1, 1.1.0, 1.0.0, 0.1.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'vue.vtaiwan.tw'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/npm-debug.log
```

如果在  package.json 改 node-bourbon -> 4.2.8 則可以安裝成功。

**Comment by chairco** [comment]
安裝成功後，`npm run dev` 會顯示下列錯誤：

```
Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/vue-loader/lib/template-loader.js:39:20)
    at LOADER_EXECUTION (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:213:10)

Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/vue-loader/lib/template-loader.js:39:20)
    at LOADER_EXECUTION (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:213:10)

Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/vue-loader/lib/template-loader.js:39:20)
    at LOADER_EXECUTION (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:213:10)

Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/vue-loader/lib/template-loader.js:39:20)
    at LOADER_EXECUTION (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:213:10)

Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/vue-loader/lib/template-loader.js:39:20)
    at LOADER_EXECUTION (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:213:10)

Unhandled rejection Error: Cannot find module 'jade'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:324:34
    at /Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.jade.render (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/consolidate/lib/consolidate.js:320:10)
    at Object.module.exports (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/vue-loader/lib/template-loader.js:39:20)
    at LOADER_EXECUTION (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
    at runSyncOrAsync (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
    at iterateNormalLoaders (/Users/chairco/OneDrive/SourceCode/django/vue.vtaiwan.tw/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
```

看起來 沒安裝 jade 套件，要執行 `npm install jade` 再次執行就會正常。
