### ISSUE TITLE
prerender failed to spawn child process - Bad argument

### ISSUE THREAD

**Issue by youchenlee** [g0v/vue.vtaiwan.tw#36]
prerender failed to spawn child process

on travis-ci (after_success.sh)
```
internal/child_process.js:289
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at capturePage (/home/travis/build/g0v/vue.vtaiwan.tw/node_modules/prerender-spa-plugin/lib/compile-to-html.js:70:26)
    at /home/travis/build/g0v/vue.vtaiwan.tw/node_modules/prerender-spa-plugin/lib/compile-to-html.js:89:11
    at _invoke (/home/travis/build/g0v/vue.vtaiwan.tw/node_modules/hapi/lib/server.js:305:20)
    at internals.Server._invoke (/home/travis/build/g0v/vue.vtaiwan.tw/node_modules/hapi/lib/server.js:375:16)
    at Items.serial (/home/travis/build/g0v/vue.vtaiwan.tw/node_modules/hapi/lib/server.js:297:14)
    at done (/home/travis/build/g0v/vue.vtaiwan.tw/node_modules/hapi/node_modules/items/lib/index.js:31:25)
    at Server.finalize (/home/travis/build/g0v/vue.vtaiwan.tw/node_modules/hapi/lib/connection.js:171:9)
    at Server.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1285:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error Command failed with exit code 1.
```

BTW,

I'm wondering why we use prerendering over SSR? 's the benefit?

**Comment by youchenlee** [comment]
finally fixed in f3c9911 + 1ce627b
