### ISSUE TITLE
更新無法手動deploy

### ISSUE THREAD

**Issue by bestian** [g0v/vue.vtaiwan.tw#80]
sudo node build/get-route.js
fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.writeFile (fs.js:1163:14)
    at Request._callback (/Users/tsung-haotang/Documents/GitHub/vue.vtaiwan.tw/build/get-route.js:37:12)
    at Request.self.callback (/Users/tsung-haotang/Documents/GitHub/vue.vtaiwan.tw/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/tsung-haotang/Documents/GitHub/vue.vtaiwan.tw/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/Users/tsung-haotang/Documents/GitHub/vue.vtaiwan.tw/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)

**Comment by jokeum** [comment]
fixed at https://github.com/g0v/vue.vtaiwan.tw/commit/455a52a3c76f2d39c15caa6d08d30a30c7f55478#diff-1b55c8a74655ae2486e82ba902475840
